### ISSUE TITLE
Activation Issue

### ISSUE THREAD

**Issue by opolanco23** [joshcummingsdesign/wp-plugin-starter#26]
Hey when trying to install without modifying anything yet. I got this error.

Can't use function return value in write context in /wp-content/plugins/testimonials/includes/class-activator.php on line 15

and that line is if( empty (get_option($option_name)) ) 

what I have found is 

https://stackoverflow.com/a/4328049/8260463

empty() needs to access the value by reference (in order to check whether that reference points to something that exists), and PHP before 5.5 didn't support references to temporary values returned from functions. I am on version 7.1 so this shouldn't be an issue.

PHP doesn't have concept of emptyness. Values that evaluate to false are empty, values that evaluate to true are non-empty.

Return value from the method always exists (even if you don't have return statement, return value exists and contains null).

From what I understand about get_option() it will return false if no option is set. so then empty(false) returns null and WordPress tries to use that.

so changing to if( !(get_option($option_name)) ) worked for me, not sure if that's the best solution

**Comment by DigitalDesignerOnline** [comment]
hey I will get on this and shoot you a message and pull request shortly with a fix for you :)

**Comment by DigitalDesignerOnline** [comment]
what is the purpose of the plugin, what is the final result when you activate the plugin etc so I can be on the same page as you when assisting

**Comment by opolanco23** [comment]
hey so the ultimate goal of the plugin is to create a custom post type, taxonomy and some custom functions but I was just registering some simple options, such as 'testimonial_per_page' => '12'.

**Comment by joshcummingsdesign** [comment]
Going to be working on a v3 of this project in the near future that should resolve how options are handled, but feel free to create a new issue if you still need help with this 👍
