### ISSUE TITLE
Is there is any way to remove hook?

### ISSUE THREAD

**Issue by phpsmashcode** [joshcummingsdesign/wp-plugin-starter#28]
Thanks, this starter plugin is very helpful. But i didn't find a way to remove hooks. Please provide an example if anyone have done this.

Kind regards,

**Comment by joshcummingsdesign** [comment]
Hi 👋 @phpsmashcode. Thanks a lot! You can add and remove hooks in `/plugin-name/includes/class-plugin.php`. There are both front-end and admin hooks there.
